name: capop_new
description: "Nova versÃ£o do app Capop"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.6
  path: ^1.8.3
  path_provider: ^2.1.1
  http: ^1.1.2
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  package_info_plus: ^5.0.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/casa.png
    - assets/images/splash.png
    - assets/images/icon.png

